tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "surface-container-high": "#292a2c",
                "surface-container-lowest": "#0d0e10",
                "on-surface": "#e3e2e5",
                "primary-fixed-dim": "#00dce6",
                "background": "#121316",
                "primary-container": "#00f2fe",
                "on-error-container": "#ffdad6",
                "on-surface-variant": "#b9cacb",
                "error-container": "#93000a",
                "surface-variant": "#343537",
                "on-tertiary-fixed-variant": "#554500",
                "tertiary": "#fff6e4",
                "surface-container": "#1f2022",
                "on-primary": "#00373a",
                "on-secondary-container": "#5a4100",
                "streak-red": "#FF0844",
                "error": "#ffb4ab",
                "on-secondary": "#402d00",
                "inverse-surface": "#e3e2e5",
                "surface-dim": "#121316",
                "outline": "#849495",
                "on-error": "#690005",
                "tertiary-fixed-dim": "#e8c423",
                "on-tertiary-container": "#725e00",
                "secondary-fixed-dim": "#f9bd22",
                "secondary-fixed": "#ffdf9f",
                "on-tertiary-fixed": "#221b00",
                "on-secondary-fixed": "#261a00",
                "on-secondary-fixed-variant": "#5c4300",
                "secondary": "#ffc640",
                "tertiary-container": "#fed83a",
                "primary-fixed": "#6ff6ff",
                "trophy-gold": "#FBBF24",
                "surface-bright": "#38393c",
                "neon-blue": "#00F2FE",
                "on-primary-fixed-variant": "#004f53",
                "tertiary-fixed": "#ffe173",
                "outline-variant": "#3a494b",
                "on-tertiary": "#3b2f00",
                "surface-gray": "#1A1C20",
                "on-background": "#e3e2e5",
                "on-primary-container": "#006a70",
                "surface": "#121316",
                "secondary-container": "#e3aa00",
                "inverse-on-surface": "#2f3033",
                "inverse-primary": "#00696f",
                "on-primary-fixed": "#002022",
                "surface-tint": "#00dce6",
                "surface-container-highest": "#343537",
                "text-silver": "#E2E8F0",
                "surface-container-low": "#1b1c1e",
                "primary": "#e0fdff"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "unit": "4px",
                "gutter": "16px",
                "margin-desktop": "64px",
                "margin-mobile": "16px",
                "container-max": "1280px"
            },
            "fontFamily": {
                "headline-lg": ["Sora"],
                "body-md": ["Hanken Grotesk"],
                "title-md": ["Sora"],
                "body-lg": ["Hanken Grotesk"],
                "headline-lg-mobile": ["Sora"],
                "stat-value": ["Sora"],
                "headline-xl": ["Sora"],
                "label-mono": ["JetBrains Mono"]
            },
            "fontSize": {
                "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
                "stat-value": ["24px", { "lineHeight": "24px", "letterSpacing": "0.02em", "fontWeight": "800" }],
                "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
                "label-mono": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500" }]
            }
        }
    }
};