import re

with open('index.html', 'r', encoding='utf-8') as f:
    html = f.read()

# 1. Update body class to remove gradient and apply Stitch fonts
html = html.replace(
    'bg-gradient-to-b from-slate-950 via-slate-900 to-black text-slate-200 font-sans selection:bg-neonCyan selection:text-black',
    'bg-background text-on-surface font-body-md min-h-screen selection:bg-primary-container selection:text-on-primary'
)

# 2. Update the 3 Banners
# The 3 banners have: `bg-gradient-to-br from-purple-950/95 via-slate-900 to-fuchsia-950/95 border-2 border-neonCyan/80 hover:border-neonCyan`
# We will add `glass-panel` and `neon-underglow` to them
banner_classes = [
    'from-purple-950/95 via-slate-900 to-fuchsia-950/95',
    'from-amber-950/95 via-stone-900 to-yellow-950/95',
    'from-blue-950/95 via-slate-900 to-cyan-950/95'
]
for bg in banner_classes:
    # Instead of replacing exact strings, we can just find 'shadow-[0_0_35px_rgba' and prepend 'glass-panel neon-underglow '
    pass

# A simpler way: we know they use `border-neonCyan/80 hover:border-amber-400` etc.
# We can just replace 'shadow-[0_0_35px' with 'glass-panel neon-underglow shadow-[0_0_35px'
html = html.replace('shadow-[0_0_35px', 'glass-panel neon-underglow shadow-[0_0_35px')

# 3. Update the Cards Grid elements
# Cards are generated by JS: `card.className = 'player-card';`
# Let's replace 'player-card' in the JS section with 'player-card glass-panel neon-underglow hover:bg-surface-container/50'
html = html.replace("card.className = 'player-card';", "card.className = 'player-card glass-panel neon-underglow hover:bg-surface-container/50';")

# Also the cards container JS: `bg-black/40` to `bg-surface-container-high/50`
html = html.replace("bg-black/40 border-b", "bg-surface-container-high/50 border-b")

# 4. Update the Podium elements in JS
# Podium uses `pilar.className = \`bg-gradient-to-b ${bgGradient}...`
# Let's add glass-panel and neon-underglow to podium
html = html.replace("pilar.className = `bg-gradient-to-b ${bgGradient}", "pilar.className = `glass-panel neon-underglow bg-gradient-to-b ${bgGradient}")

# 5. Global font updates for headers from font-mono to font-title-lg or just keep font-mono but use the Stitch font
# Note: we already linked JetBrains Mono, so font-mono will automatically look better!
# Let's replace Orbitron with JetBrains Mono in JS Chart
html = html.replace("'Orbitron'", "'JetBrains Mono'")

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(html)
print("Skin applied to index.html successfully!")
